// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RocketLeagueStats.Core.Persistence;

#nullable disable

namespace RocketLeagueStats.Core.Persistence.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20260503090552_AddTeamMetadataAndPlayerStats")]
    partial class AddTeamMetadataAndPlayerStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.EventParticipant", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Shortcut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamNum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "PlayerName", "Role");

                    b.HasIndex("MatchGuid", "PlayerName")
                        .HasDatabaseName("IX_EventParticipants_MatchGuid_PlayerName");

                    b.HasIndex("PlayerName", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_EventParticipants_PlayerName_TimestampUtc");

                    b.ToTable("EventParticipants", (string)null);
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.EventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchGuid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventName", "TimestampUtc")
                        .HasDatabaseName("IX_Events_EventName_TimestampUtc");

                    b.HasIndex("MatchGuid", "Id")
                        .HasDatabaseName("IX_Events_MatchGuid_Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.Match", b =>
                {
                    b.Property<string>("MatchGuid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Arena")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueColorPrimary")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueColorSecondary")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueTeamName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DestroyedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InitializedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEventAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrangeColorPrimary")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrangeColorSecondary")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrangeTeamName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerTeamNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchGuid");

                    b.HasIndex("EndedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Matches_EndedAtUtc");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.MatchSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchGuid", "Id")
                        .HasDatabaseName("IX_MatchSnapshots_MatchGuid_Id");

                    b.ToTable("MatchSnapshots", (string)null);
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.PlayerMatchStats", b =>
                {
                    b.Property<string>("MatchGuid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Shortcut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Touches")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchGuid", "Shortcut");

                    b.HasIndex("PlayerName")
                        .HasDatabaseName("IX_PlayerMatchStats_PlayerName");

                    b.ToTable("PlayerMatchStats", (string)null);
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.EventParticipant", b =>
                {
                    b.HasOne("RocketLeagueStats.Core.Persistence.Entities.EventRecord", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.EventRecord", b =>
                {
                    b.HasOne("RocketLeagueStats.Core.Persistence.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.MatchSnapshotRecord", b =>
                {
                    b.HasOne("RocketLeagueStats.Core.Persistence.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RocketLeagueStats.Core.Persistence.Entities.PlayerMatchStats", b =>
                {
                    b.HasOne("RocketLeagueStats.Core.Persistence.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
